Update Makefile - lack of -std=c++11 flag
Lack of -std=c++11 caused a long list of errors with the following at the begining:

error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \